### ISSUE TITLE
Chapter links not working anymore.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/AmiKo-Android#1]
1. Open The App
2. Search for "Ponstan" in the "Präparat" Tab.
3. Select Ponstan
4. Swipe from right to left to get the chapter links.
5. Select any chapter
6. Error shows up. See below [ This works on AmiKo for iPhone/iPad ]
![martinfries](https://user-images.githubusercontent.com/4953/44708549-b2279900-aaa7-11e8-817c-76323c56b7c8.png)

**Comment by zdavatz** [comment]
See: https://ywesee.slack.com/files/U27FC8WLA/FEL5J3RPU/20181205_163344.mp4

**Comment by b123400** [comment]
I've reproduced the issue, will try to fix it after migrating the build system to Gradle. Interesting though, in the emulator when I click on any chapter, the browser did nothing, instead the same error message is print through the error log.

**Comment by zdavatz** [comment]
This is indeed very interesting! Ok. Looking forward to the gradle Pull-Request for Android Studio!

**Comment by zdavatz** [comment]
This error is gone with commit 60bb6411e0cd7d7c8967ab120 but the chapter links now do not jump to the correct chapters. See #8
