### ISSUE TITLE
Voll-Text-Suche hinzufügen

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/AmiKo-Android#114]
Siehe: https://github.com/zdavatz/AmiKo-iOS/issues/91

Bitte mit Windows und macOS AmiKo Volltext-Suche vergleichen.

1. Applikation starten.
2. Die Abkürzungen für _Volltext-Suche_ sind
2.1 iPhone/iPad Portrait Mode: `VTS` de, `RPT` fr, `FTS` en 
2.2 iPad Landscape und Searchbar Placeholder: 
`Volltext Suche`
`Recherche plein-texte`
`Fulltext Search` 
2.3 iPhone Landscape: `Volltext`, `Plein-texte`, `Fulltext`
3. Wenn der Benutzer `VTS` anwählt, dann kommt die _Volltext-Suche_.
4. User gibt "SAPP" ein.
5. Das erste Resultat wird im Hauptfenster gezeigt.
6. Der Benutzer wählt im Hauptfenster `SAPP` an.
7. Das zweite Ergebnis wird im Hauptfenster angezeigt, mit einem _Hamburger_ auf beiden Seiten. Wenn der Benutzer auf den _Hamburger_ auf der rechten Seite klickt, wird 9 angezeigt. Wenn der Benutzer auf den _Hamburger_ auf der linken Seite klickt, gelangen Sie zurück zu 5. Natürlich können auch 5 oder 9 auch reingewischt werden. So können wir den Fachinfo View mit den _Hamburgern_ auf beiden Seiten nutzen. Gleiches Prinzip wie bei der Fachinfo.
8. Der Benutzer wählt eine FI aus und gelangt mit dem Wort zum ersten markierten Abschnitt.
9. Der Benutzer kann die Ergebnisübersicht auch von rechts einblenden. Wenn der Benutzer etwas aus der Ergebnisübersicht auswählt, wird das Hauptfenster neu sortiert.

Übersetzt mit www.DeepL.com/Translator
<img width="1339" alt="Screenshot 2019-07-13 at 18 31 44" src="https://user-images.githubusercontent.com/4953/61174206-756c6f80-a59d-11e9-85c4-3399942c388b.png">

**Comment by zdavatz** [comment]
![A3BDD77D-F359-48BB-8432-4E6910C6F293](https://user-images.githubusercontent.com/4953/62284256-f8297180-b45b-11e9-9d6f-6d4c81f3d22e.jpeg)

**Comment by b123400** [comment]
Meine Todo-Liste:

- [x] Herunterladen und machen mit frequence.db Datei
- [x] Lesen vom Database
- [x] Zeigen Suchergebnis
- [ ] Verbindung zu Artikel
- [ ] Markieren die Schlüsselwörtern
- [ ] Suche in Favoriten
- [ ] Bekräftigte "update" funktion
