### ISSUE TITLE
Gdrive Sync für AmiKo/CoMed Android

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/AmiKo-Android#174]
AmiKo/CoMed für Android Daten müssen in der Gdrive Cloud gespeichert werden können. Verliert der User sein Telefon, sollte der die Daten wieder aus dem Backup einlesen können.

Siehe auch: https://github.com/zdavatz/AmiKo-iOS/issues/112

**Comment by b123400** [comment]
Meine Todo-Liste.
- [ ] Local -> Google Drive Migration:
  - [x] Hochladen
  - [ ] Runterladen
- [ ] Google Drive -> Local Migration
  - [ ] Dateien auf Google Drive löschen?
----
- [x] Arzt Datei lesen
- [x] Arzt Datei schreiben 
- [x] Arzt "signature.png" Datei lesen 
- [x] Arzt "signature.png" Datei schreiben
- [x] Amk Dateien lesen
- [x] Amk Dateien schreiben
- [ ] Patienten lesen
- [ ] Patienten schreiben
----
- UI updaten wann Google Drive dateien geändert
  - [ ] Arzt
  - [ ] Prescription
  - [ ] Patienten Liste
  - [ ] Patient
  - [ ] AMK liste
----
- [ ] Sync interval
- [ ] Setting View

**Comment by zdavatz** [comment]
ja, wenn der User seine Datei im App löscht, sollte sie in der Cloud auch gelöscht werden.
