### ISSUE TITLE
Latest Database is not distributed with new release

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/AmiKo-Android#198]
1. Make a new release with `make publishBundle`
2. Update the Release on your Android phone.
3. The app does not show the latest database.

**Comment by b123400** [comment]
I cannot reproduce the issue.
Can you see the database files being downloaded when you build the app? e.g. Look at the db files in the `build` directory, to see if they are latest

**Comment by zdavatz** [comment]
Yes, the files are being downloaded when I do `make publishBundle`. I think the issue lies with the way the .aab file is unpacked, if there is already an AmiKo/CoMed App installed on the phone. Somehow the App Update does not overwrite the DB if the DB of the Update is newer.

**Comment by b123400** [comment]
I tried many times and different setup, but still cannot reproduce the issue.
Is the report also not updated? Or just database?

**Comment by zdavatz** [comment]
Can you try with the latest release 1.9.0? I did not check the report. Will do so today.

**Comment by zdavatz** [comment]
ok. Seems to work as well on my Android 10.
