### ISSUE TITLE
Missing desitin_icon

### ISSUE THREAD

**Issue by b123400** [zdavatz/AmiKo-Android#2]
Here there is code referencing a file `desitin_icon` but such file is not in this repository.

https://github.com/zdavatz/AmiKo-Android/blob/089c3768eca3bbf73f2adff4837b768eb6703f10/src/com/ywesee/amiko/MainActivity.java#L258

**Comment by zdavatz** [comment]
All the icons are here. https://github.com/zdavatz/AmiKo-Android/tree/master/logos Where is that Icon supposed to be shown. We may not need it anymore.

**Comment by zdavatz** [comment]
How large is the Icon supposed to be?

**Comment by b123400** [comment]
Oh it's not the app icon. By reading the code, it seems to be an icon for an alert dialog.

The size varies

  | ldpi (120 dpi)       (Low density screen) | mdpi (160 dpi)       (Medium density screen) | hdpi (240 dpi)       (High density screen) | xhdpi (320 dpi)       (Extra-high density screen)
-- | -- | -- | -- | --
Dialog Icon Size | 24 x 24 px | 32 x 32 px | 48 x 48 px | 64 x 64 px

ref: https://developer.android.com/guide/practices/ui_guidelines/icon_design_dialog

**Comment by zdavatz** [comment]
Ok, please see that attached icons in the requested sizes, plus the original.
![des_icon-app weiss](https://user-images.githubusercontent.com/4953/49697004-68744180-fbb2-11e8-8471-05a2119a904a.png)
![desitin_24x24](https://user-images.githubusercontent.com/4953/49697005-68744180-fbb2-11e8-96fa-efad33e0362c.png)
![desitin_32x32](https://user-images.githubusercontent.com/4953/49697006-690cd800-fbb2-11e8-8607-eb6557614bea.png)
![desitin_48x48](https://user-images.githubusercontent.com/4953/49697007-690cd800-fbb2-11e8-919e-5085b7672f4d.png)
![desitin_64x64](https://user-images.githubusercontent.com/4953/49697008-690cd800-fbb2-11e8-85e6-fa822b5e8320.png)

**Comment by zdavatz** [comment]
please use them in PR.

**Comment by b123400** [comment]
thank you!
