### ISSUE TITLE
Sign with Photo works, but rotation is still wrong

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/AmiKo-Android#36]
Sign with Photo works, but rotation is still wrong, see below, image is in landscape mode, but I took the image in portrait mode.
![screenshot_20190117-181057](https://user-images.githubusercontent.com/4953/51335967-aacb5100-1a83-11e9-80b6-a1bdaadc3b31.png)

It works if I use a screenshot image.

**Comment by b123400** [comment]
I tried to take images with all 4 orientations and they are fine on my machine. Do you mind sharing the image that gets rotated?

**Comment by zdavatz** [comment]
![img_20190117_181024](https://user-images.githubusercontent.com/4953/51400298-563dd980-1b48-11e9-94f0-3ee431ffe46a.jpg)

**Comment by zdavatz** [comment]
See: https://stackoverflow.com/questions/29971319/image-orientation-android/32747566#32747566 and https://stackoverflow.com/questions/20478765/how-to-get-the-correct-orientation-of-the-image-selected-from-the-default-image

**Comment by zdavatz** [comment]
works, thank you!
