### ISSUE TITLE
App hangs when sliding from right to left in patient view

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/AmiKo-Android#37]
The App hangs when sliding from right to left while in the patient view, see:

https://gist.github.com/zdavatz/0da8247f7ef8c2cac896909b78a74457

**Comment by b123400** [comment]
Strange... It works on my machine, and there isn't any error in the log above. I am currently asking for permission to read address book when the drawer is opened, maybe the timing is bad that it blocked some UI events.

- When you slide in patient view, did you see the drawer showing from the right?
- Is the entire app hang? How about pressing the top back button and the bottom back button (the one next to the home button)?

**Comment by zdavatz** [comment]
entire Apps hangs, then crashes. I can slide in the drawer. After that it hangs.

**Comment by zdavatz** [comment]
Ok, now the addresses came. I guess the reason for the slow response of the App is, that I got about 3'000 entries in my address book. How can we speed this up?

**Comment by zdavatz** [comment]
Please try these solutions for faster contacts loading: https://stackoverflow.com/questions/17798613/getting-android-contacts-details-very-slow

**Comment by b123400** [comment]
Ok, thank you! Let me try

**Comment by zdavatz** [comment]
This also contains some useful links/hints ideas: https://stackoverflow.com/questions/12109391/getting-name-and-email-from-contact-list-is-very-slow
