### ISSUE TITLE
Database Update no longer works.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/AmiKo-Android#50]
Since Version 1.4.3 - fd7068d5e98a69c3d77587982910ce03deb7061f - the update Function no longer works. Steps to reproduce are:

1. Install latest version of the App from here: http://pillbox.oddb.org/AmiKo-Android-amiko-release.apk
2. Click the Menu Button in the Top-Right corner.
3. Click _Update_.
4. Wait for the Update to finish.
5. After the Update select any medication to show the Fachinfo. 
6. App *crashes*.
7. Restart the App.
8. There is no more data there. You can not search anything anymore.

**Comment by b123400** [comment]
Sorry I tried a few times but I cannot reproduce the bug. Do you have any crash log?

**Comment by zdavatz** [comment]
I am getting this:
```
02-04 21:23:11.960 18190 18190 D Utilities: File /storage/emulated/0/Download/amiko_db_full_idx_de.zip does not exists. No need to delete.
02-04 21:23:11.961 18190 18190 D Utilities: File /storage/emulated/0/Download/amiko_report_de.html does not exists. No need to delete.
02-04 21:23:11.971 16987 17005 W DownloadManager: Path appears to be invalid: /storage/emulated/0/Download/amiko_db_full_idx_de.zip
02-04 21:23:11.991 16987 17005 W DownloadManager: Path appears to be invalid: /storage/emulated/0/Download/amiko_report_de.html
02-04 21:23:12.432  1923  5607 W NotificationService: Toast already killed. pkg=com.ywesee.amiko.de callback=android.app.ITransientNotification$Stub$Proxy@ad2738d
02-04 21:23:12.870  1923  2387 E NotificationService: Package enqueue rate is 9.575768. Shedding 0|com.android.providers.downloads|0|1:com.ywesee.amiko.de|10008. package=com.android.providers.downloads
02-04 21:23:30.965  1923  5607 I NotificationService: cancelToast pkg=com.ywesee.amiko.de callback=android.app.ITransientNotification$Stub$Proxy@e74a55a
02-04 21:23:30.965  1923  5607 W NotificationService: Toast already cancelled. pkg=com.ywesee.amiko.de callback=android.app.ITransientNotification$Stub$Proxy@e74a55a
02-04 21:23:32.951  1923  5607 W NotificationService: Toast already killed. pkg=com.ywesee.amiko.de callback=android.app.ITransientNotification$Stub$Proxy@26fae
02-04 21:23:41.969 18190 18465 D DataBaseHelper: Unzipped file amiko_db_full_idx_de.db (243713kB)
02-04 21:23:42.301 18190 18465 D DataBaseHelper: opening database /data/user/0/com.ywesee.amiko.de/databases/amiko_db_full_idx_de.db...
02-04 21:23:42.763 18190 18465 E DefaultDatabaseErrorHandler: Corruption reported by sqlite on database: /data/user/0/com.ywesee.amiko.de/databases/amiko_db_full_idx_de.db
02-04 21:23:42.763 18190 18465 E DefaultDatabaseErrorHandler: deleting the database file: /data/user/0/com.ywesee.amiko.de/databases/amiko_db_full_idx_de.db
02-04 21:23:43.045 18190 18465 E SQLiteLog: (1) no such table: amikodb
02-04 21:23:44.011 18190 18200 I ywesee.amiko.d: Background concurrent copying GC freed 117214(16MB) AllocSpace objects, 0(0B) LOS objects, 33% free, 48MB/72MB, paused 103us total 122.641ms
02-04 21:23:44.283 18190 18479 E SQLiteLog: (1) no such table: amikodb
02-04 21:23:44.374   806   806 D SurfaceFlinger: duplicate layer name: changing com.ywesee.amiko.de/com.ywesee.amiko.MainActivity to com.ywesee.amiko.de/com.ywesee.amiko.MainActivity#2
```

**Comment by zdavatz** [comment]
Does this directory exist on your device: `/data/user/0/com.ywesee.amiko.de/databases/`?

**Comment by zdavatz** [comment]
When I update from the store, I also get this:
```
02-05 13:06:00.056  8570  8570 D Utilities: File /storage/emulated/0/Download/amiko_db_full_idx_de.zip does not exists. No need to delete.
02-05 13:06:00.056  8570  8570 D Utilities: File /storage/emulated/0/Download/amiko_report_de.html does not exists. No need to delete.
02-05 13:06:00.067  8352  8814 W DownloadManager: Path appears to be invalid: /storage/emulated/0/Download/amiko_db_full_idx_de.zip
02-05 13:06:00.089  8352  8814 W DownloadManager: Path appears to be invalid: /storage/emulated/0/Download/amiko_report_de.html
```

**Comment by zdavatz** [comment]
This seems to have helped:
```
As mentioned in the comments above, clearing the Download manager cache and data resolves this problem on Android 9 Pie. To clear these settings, you need to go to Apps & notifications, click the option to See all apps, tap the options menu in the upper-right corner, select Show system, select Download Manager from the list, tap on Storage, then clear the cache and storage.
```

**Comment by zdavatz** [comment]
But when I install the latest version of the App I still get: 
```
02-05 14:49:23.603 10645 11249 E SQLiteLog: (1) no such table: amikodb
```
and then
```
02-05 14:49:23.612   809   809 D SurfaceFlinger: duplicate layer name: changing com.ywesee.amiko.de/com.ywesee.amiko.MainActivity to com.ywesee.amiko.de/com.ywesee.amiko.MainActivity#1
02-05 14:49:24.361 10645 11250 E SQLiteLog: (1) no such table: amikodb
02-05 14:49:24.371   809   809 D SurfaceFlinger: duplicate layer name: changing com.ywesee.amiko.de/com.ywesee.amiko.MainActivity to com.ywesee.amiko.de/com.ywesee.amiko.MainActivity#1
```

**Comment by zdavatz** [comment]
There seems to be a discrepancy between the paths: 
```
02-05 15:04:38.936 14038 14058 D DataBaseHelper: opening database /data/user/0/com.ywesee.amiko.de/databases/amiko_db_full_idx_de.db...
02-05 15:04:38.937 14038 14038 I System.out: Found application data folder is in /data/user/0/com.ywesee.amiko.de/files
02-05 15:04:38.942 14038 14058 E SQLiteLog: (1) no such table: amikodb

```

**Comment by b123400** [comment]
The path `/data/user/0/com.ywesee.amiko.de/databases/` does not exist on my phone, the path for database on my phone is `/data/data/com.ywesee.amiko.de/databases/`. It works on my machine, I am thinking maybe the new version of Android has changed some paths and the download code is not compatible with that. Let me try to reproduce it with the latest OS and review the related code.

**Comment by zdavatz** [comment]
My phone is running Android 9, updated January 5th 2019.

**Comment by b123400** [comment]
After reading through the source code, I think the main problem is the download file is corrupted (at least `DataBaseHelper` thinks it is), the default behaviour of the system is to delete the corrupted file, and so the database file is missing.

Also, the `DownloadManager: Path appears to be invalid:` log seems to be unrelated. It comes from https://android.googlesource.com/platform/packages/providers/DownloadProvider/+/8ec0057/src/com/android/providers/downloads/Helpers.java#371 , which is a function that checks if the location is in the app's data folder. In our case, we are downloading to the shared Download folder, so it is ok.

I will try to add more logs for better debugging. I will also modify the logic such that, the database is replaced only when the new one is valid, if it is corrupted, the old database will be kept, is that ok?

Also, seems like the database is regenerated everyday? Do you have a copy of the old database that caused the problem? (The one generated on 4th of Feb?)

**Comment by zdavatz** [comment]
I do not think that the database is corrupted. AmiKo for iPhone uses the same database, and there were no problems there. Also, the version from the Play Store did work on the same day.

**Comment by zdavatz** [comment]
It may be, that Android thinks the Database is corrupted because the path was wrong. But if the DB was only partially download, then we could use an exception handling for that.

**Comment by zdavatz** [comment]
> I will try to add more logs for better debugging. I will also modify the logic such that, the database is replaced only when the new one is valid, if it is corrupted, the old database will be kept, is that ok?
Ok.

**Comment by zdavatz** [comment]
> Also, seems like the database is regenerated everyday? Do you have a copy of the old database that caused the problem? (The one generated on 4th of Feb?)

No, we do not keep old copies of the DB. You can grab the latest one here: http://pillbox.oddb.org/amiko_db_full_idx_de.zip

**Comment by zdavatz** [comment]
Now the DB is not downloaded at all. My phone just stays here and nothing happens:
![screenshot_20190210-215841](https://user-images.githubusercontent.com/4953/52539526-5a43cc80-2d7f-11e9-9ad1-f5ea02bd9859.png)

**Comment by zdavatz** [comment]
I am still getting these errors:
```
02-10 22:31:36.111 26685 26685 D Utilities: File /storage/emulated/0/Download/amiko_db_full_idx_de.zip does not exists. No need to delete.
02-10 22:31:36.112 26685 26685 D Utilities: File /storage/emulated/0/Download/amiko_report_de.html does not exists. No need to delete.
02-10 22:31:36.121 18009 18032 W DownloadManager: Path appears to be invalid: /storage/emulated/0/Download/amiko_db_full_idx_de.zip
02-10 22:31:36.138 18009 18032 W DownloadManager: Path appears to be invalid: /storage/emulated/0/Download/amiko_report_de.html
02-10 22:31:36.247  1948  1948 I NotificationService: Cannot find enqueued record for key: 0|com.android.providers.downloads|0|1:com.ywesee.amiko.de|10008
02-10 22:31:39.160  1948  1948 I NotificationService: Cannot find enqueued record for key: 0|com.android.providers.downloads|0|1:com.ywesee.amiko.de|10008
```

**Comment by b123400** [comment]
The above logs does not show any error, they are warnings and it's actually valid.

> Also, the `DownloadManager: Path appears to be invalid:` log seems to be unrelated. It comes from https://android.googlesource.com/platform/packages/providers/DownloadProvider/+/8ec0057/src/com/android/providers/downloads/Helpers.java#371 , which is a function that checks if the location is in the app's data folder. In our case, we are downloading to the shared Download folder, so it is ok.

But it is very weird that the app hangs, I didn't modified any code related to download. It seems `DownloadManager` on Android 9 is not reliable, do you have more logs? Otherwise maybe I should reimplement everything related myself, giving up on using `DownloadManager`

**Comment by b123400** [comment]
I've tried everything I can, on the machine or many emulators, but they all works.

**Comment by zdavatz** [comment]
What Android Version is your phone?

**Comment by zdavatz** [comment]
With this [workaround](https://stackoverflow.com/questions/52055952/downloadmanager-requests-delayed-on-android-pie), the download works again, BUT after initializing the newly download database, I click a Fachinfo and then the App crashes. After the restart of the App, I can not search anything anymore.

**Comment by zdavatz** [comment]
After the download of the new DB and initializing the new DB I get:
```
02-11 21:07:09.612 28436 28743 D DataBaseHelper: opening database /data/user/0/com.ywesee.amiko.de/databases/amiko_db_full_idx_de.db...
02-11 21:07:09.893 28436 28743 E SQLiteLog: (1) no such table: amikodb
02-11 21:07:10.757 28436 28446 I ywesee.amiko.d: Background concurrent copying GC freed 128895(16MB) AllocSpace objects, 0(0B) LOS objects, 33% free, 47MB/71MB, paused 89us total 123.735ms
02-11 21:07:11.040 28436 28752 E SQLiteLog: (1) no such table: amikodb
```

**Comment by zdavatz** [comment]
So downloading and initializing the new DB now actually works, but then I get:
```
02-11 21:14:07.355 29338 29338 E SQLiteLog: (1) no such table: amikodb
02-11 21:14:07.433 29338 29338 E AndroidRuntime: Process: com.ywesee.amiko.de, PID: 29338
02-11 21:14:07.433 29338 29338 E AndroidRuntime: android.database.sqlite.SQLiteException: no such table: amikodb (code 1 SQLITE_ERROR): , while compiling: SELECT DISTINCT _id, title, auth, atc, substances, regnrs, atc_class, tindex_str, application_str, indications_str, customer_id, pack_info_str, add_info_str, ids_str, titles_str, content, style_str FROM amikodb WHERE _id=3
02-11 21:14:07.433 29338 29338 E AndroidRuntime: 	at com.ywesee.amiko.DBAdapter.getRecord(DBAdapter.java:517)
02-11 21:14:07.433 29338 29338 E AndroidRuntime: 	at com.ywesee.amiko.DBAdapter.searchId(DBAdapter.java:505)
02-11 21:14:07.433 29338 29338 E AndroidRuntime: 	at com.ywesee.amiko.MainActivity$CustomListAdapter$2.onClick(MainActivity.java:2035)
02-11 21:14:07.440  1948  7093 W ActivityManager:   Force finishing activity com.ywesee.amiko.de/com.ywesee.amiko.MainActivity
02-11 21:14:07.593  1948  2911 I ActivityManager: Process com.ywesee.amiko.de (pid 29338) has died: vis  TOP
```

**Comment by b123400** [comment]
My Android is 8.1.

I tried to download the database file manually and it does not seems to work?

```
▶ curl http://pillbox.oddb.org/amiko_db_full_idx_de.zip > ./t.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:14 --:--:--     0
curl: (7) Failed to connect to pillbox.oddb.org port 80: Network is unreachable
```

Also I just find out all the download links in the app is HTTP and [Starting with Android 9 (API level 28), cleartext support is disabled by default](https://developer.android.com/training/articles/security-config). Maybe that's what caused the problem, does the pillbox server support https?

https://www.pillbox.oddb.org (with a www) seems to have https setup, but the certificate is wrong.

**Comment by zdavatz** [comment]
I just had to switch the download IP, because the primary one went down. You should be able to download again shortly. Can you disable "https" and only use http for downloading?

**Comment by zdavatz** [comment]
works with #52
