### ISSUE TITLE
still getting double and triple patient import

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/AmiKo-Android#77]
1. Import 1.amk of patient A.
2. Import 1.amk of paitent A again.
3. Now there are two identical patient As in the local DB.
4. There should only be one patient A if you import multiple .amk of the same patient.

**Comment by zdavatz** [comment]
![](https://i.imgur.com/MHFDVAQ.png)

**Comment by b123400** [comment]
That is probably caused by a hash mismatch, how did you generate the amk file? AMK files generated before 1.5.6 should has the wrong hash. Is it possible to have an amk file (without all the sensitive information) for me to test?

**Comment by zdavatz** [comment]
seems to be working with: 323cbff824406100ff7c6bd9914b40e481000ff1

**Comment by zdavatz** [comment]
Import this amk twice or three times (do not forget to rename it to .amk first).
[RZ_2019-03-08T110908.amk.txt](https://github.com/zdavatz/AmiKo-Android/files/2976854/RZ_2019-03-08T110908.amk.txt)

**Comment by zdavatz** [comment]
same problem here: 
[RZ_2019-03-08T110811.amk.txt](https://github.com/zdavatz/AmiKo-Android/files/2976874/RZ_2019-03-08T110811.amk.txt)

**Comment by zdavatz** [comment]
It seems like the .amk files that where created using AmiKo for Windows are causing the problem.

**Comment by zdavatz** [comment]
same problem here: 
[RZ_2019-03-04T083030.amk.txt](https://github.com/zdavatz/AmiKo-Android/files/2976945/RZ_2019-03-04T083030.amk.txt)
