### ISSUE TITLE
Add gradle build option for "CoMed"

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/AmiKo-Android#9]
The French version of the app is called "CoMed Desitin". We have to be able to build "CoMed_Desitin.apk" using gradle as well. Building "CoMed Desitin" should select the French database.

Note:
On iOS we localized the App so the language of the App is selected based on the language settings for the device. So in the Future we could just release one App and add a settings field for the database selection.

**Comment by b123400** [comment]
Are all the difference between AmiKo and CoMed listed in the readme? 
So Gradle should at least perform the following:

- [ ] Download database to assets
- [ ] Download report file to assets
- [ ] Update launch icon
- [ ] Update splash screen
- [ ] Update package name
- [ ] Update `strings.xml`

**Comment by zdavatz** [comment]
Splash Screen and Launch Icon are the same for AmiKo and CoMed. The main differences are the DB, Report-File and the interface. They are all in French.

**Comment by zdavatz** [comment]
ComMed-Desitin. apk is a separate apk.

**Comment by zdavatz** [comment]
The README.md also talks about the different Look and Feels the App can be built in. But we no longer support the med-drugs Look and Feel.

**Comment by b123400** [comment]
I've got it partly working. Just wonder, if the med-drugs LNF is not supported anymore, can I delete the related code and do a bit of refactor? Or do you prefer leaving it there for future usage?

**Comment by zdavatz** [comment]
You can remove the med-drugs LNF and do a refactor.
